DB初期化スクリプトの修正
arima0714/SaladBoard pull request #1
Opened 2022-04-13 05:45 UTC by arima0714

動作確認方法は

1. docker-compose up -d database
2. docker-compose run --rm flyway-clean
3. docker-compose run --rm flyway-migrate

です。

2022-04-13 05:59 UTC, yumemi-nshibata commented on flyway/sql/V1.0.0__init.sql
> +-- 投稿マスタ
マスタ・・・マスタ？
投稿データはマスタデータではなく、トランザクションデータになるのかなぁと
説明としては以下記事のとおりです
https://wa3.i-3-i.info/diff372data.html

2022-04-13 06:00 UTC, yumemi-nshibata commented on flyway/sql/V1.0.0__init.sql
> +    email    varchar(100) NOT NULL COMMENT 'email',
メールアドレスって規格で100文字が上限なのでしたっけ？

2022-04-13 06:00 UTC, yumemi-nshibata commented on flyway/sql/V1.0.0__init.sql
> +    password varchar(100) NOT NULL COMMENT 'password',
パスワードはどのように保存する想定ですか？そのまま生文？

2022-04-13 06:09 UTC, arima0714 commented on flyway/sql/V1.0.0__init.sql
> +-- 投稿マスタ
マスタデータ・トランザクションデータの分類を今知りました。

僕は、現在作成するテーブルの情報の全て（ユーザー情報・投稿・イイネ）はトランザクションデータになると思うのですが、その認識であってますでしょうか？

2022-04-13 06:10 UTC, OskaMathis reviewed
サラッと見て気になった箇所だけコメントしました。

2022-04-13 06:10 UTC, OskaMathis commented on flyway/sql/V1.0.0__init.sql
> +    date    datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'date',
[should]
COMMENTにカラム名を書くだけなら別にCOMMENTする意味ないかなと。

今回はDB設計がかなりシンプルなのでぶっちゃけCOMMENT無くても問題なさそうに見えますが、
COMMENTするならちゃんと説明した方が良いです。

```suggestion
    body    text NOT NULL COMMENT '本文',
    date    datetime DEFAULT CURRENT_TIMESTAMP COMMENT '投稿日時',
```

2022-04-13 06:10 UTC, OskaMathis commented on flyway/sql/V1.0.0__init.sql
> +  COLLATE = utf8mb4_unicode_ci comment ='投稿マスタ'
[nits]
`=` の右側の半角スペースが欲しいのと、
折角インデントが揃えてあるので、COMMENTも改行した方が見栄えが良いと思いました。

```suggestion
  COLLATE = utf8mb4_unicode_ci
  COMMENT = '投稿マスタ'
```

2022-04-13 06:10 UTC, OskaMathis commented on flyway/sql/V1.0.0__init.sql
>  -- ユーザマスタ
マスタという言い方がそもそも曖昧だという前提の上で、個人的にシックリ来た記事を貼っておきます。
https://honey8823.hateblo.jp/entry/2015/08/04/172902

2022-04-13 06:11 UTC, OskaMathis commented on flyway/sql/V1.0.0__init.sql
> +-- 投稿マスタ
重複してコメントしてしまった:sweat:
https://github.com/arima0714/SaladBoard/pull/1#discussion_r849109675

2022-04-13 06:11 UTC, arima0714 commented on flyway/sql/V1.0.0__init.sql
> +    email    varchar(100) NOT NULL COMMENT 'email',
正直に言ってノリで100文字に設定していました。
調査して、修正します。

2022-04-13 06:15 UTC, arima0714 commented on flyway/sql/V1.0.0__init.sql
> +    password varchar(100) NOT NULL COMMENT 'password',
「パスワード生文ってアカンよなぁ」と思いながら生文の想定でした。

2022-04-13 06:24 UTC, mizutoki79 requested changes

2022-04-13 06:24 UTC, mizutoki79 commented on flyway/sql/V1.0.0__init.sql
> +    password varchar(100) NOT NULL COMMENT 'password',
参考までにmysql.userテーブルでパスワードハッシュのカラムはTEXT型を使用していました
```
mysql> SHOW COLUMNS FROM user WHERE Field IN ('Host', 'User', 'authentication_string');
+-----------------------+----------+------+-----+---------+-------+
| Field                 | Type     | Null | Key | Default | Extra |
+-----------------------+----------+------+-----+---------+-------+
| Host                  | char(60) | NO   | PRI |         |       |
| User                  | char(32) | NO   | PRI |         |       |
| authentication_string | text     | YES  |     | NULL    |       |
+-----------------------+----------+------+-----+---------+-------+
3 rows in set (0.02 sec)
```

2022-04-13 06:24 UTC, mizutoki79 commented on flyway/sql/V1.0.0__init.sql
> -    created_at                datetime            DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
今回の作る範囲では不要かもしれませんが、created_at残しておくといつから利用開始とか表示できたり、何かと便利かと思います

2022-04-13 06:24 UTC, mizutoki79 commented on flyway/sql/V1.0.0__init.sql
> +    user_id int unsigned NOT NULL COMMENT 'user_id',
他のテーブルのカラムを参照するときは外部キー制約を貼りましょう
https://dev.mysql.com/doc/refman/5.6/ja/create-table-foreign-keys.html

2022-04-13 06:24 UTC, mizutoki79 commented on flyway/sql/V1.0.0__init.sql
> +    user_id int unsigned NOT NULL COMMENT 'user_id',
こちらのpost_id,use_idも共に外部キー制約

2022-04-13 06:24 UTC, mizutoki79 commented on flyway/sql/V1.0.0__init.sql
> +    date    datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'date',
全体的にカラム名とほぼ同じでCOMMENTを残している意味が無いので、もうちょっと分かりやすい説明を残してください

2022-04-13 06:24 UTC, mizutoki79 commented on flyway/sql/V1.0.0__init.sql
> +    PRIMARY KEY (post_id)
post_idだけがPRIMARYだと一つのポストに対して、全ユーザー共通で1度しかイイネできなくなります

2022-04-13 06:28 UTC, mizutoki79 commented on flyway/sql/V1.0.0__init.sql
> +    password varchar(100) NOT NULL COMMENT 'password',
https://dev.mysql.com/doc/refman/5.6/ja/password-hashing.html
関数噛ますだけでハッシュになります

2022-04-13 06:48 UTC, OskaMathis commented on flyway/sql/V1.0.0__init.sql
> -    created_at                datetime            DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
[imo]
不具合調査に役立ったりするので、登録日時・更新日時とかはアプリケーション上で直接必要ない場合でも記録しておくと便利ですね。

2022-04-13 08:46 UTC, nozawama commented on flyway/sql/V1.0.0__init.sql
> +    like_id int unsigned NOT NULL AUTO_INCREMENT COMMENT 'like_id',
いいねにidを持たせても良いですが、複数カラムの組み合わせに対して主キーを設定することもできます。
https://dev.mysql.com/doc/refman/5.6/ja/create-table-foreign-keys.html#:~:text=PRIMARY%20KEY(category%2C%20id)
例えば今回であれば、いいねをしたユーザのidと対象のポストのidの組み合わせを一意にすることで、各ユーザが各ポストに対して1度ずついいねできるようになります。

ただここは課題の要件として具体的に定まっていないと思うので、例えば各ユーザが各ポストに対して複数回いいねできるようなものを完成形としてイメージしていた場合などは今のままが良いと思います。

2022-04-13 08:48 UTC, OskaMathis commented on flyway/sql/V1.0.0__init.sql
> +    COMMENT = 'ユーザトランザクション'
[ask]
CREATE TABLEの中身とインデント合わせた感じですかね？
(DEFAULT CHARSETやCOLLATEと合わせてほしかった)

2022-04-13 08:48 UTC, OskaMathis commented on flyway/sql/V1.0.0__init.sql
> +    COMMENT = 'ユーザトランザクション'
[imo]
フォーマッタに任せてしまうのも手だと思います。

2022-04-13 08:56 UTC, arima0714 commented on flyway/sql/V1.0.0__init.sql
> +    COMMENT = 'ユーザトランザクション'
> [ask]
CREATE TABLEの中身とインデント合わせた感じですかね？
(DEFAULT CHARSETやCOLLATEと合わせてほしかった)

特にどこに合わせるということをやったわけではないです。intellijのmysqlフォーマッタにかけただけでした。これに関しては自分も `DEFAULT CHARSET` や `COLLATE` に合って欲しかったです。ただ、手動修正をしていると抜けがあって結果として統一感(?)が失われてしまう気がしたので、このような形にしました。

2022-04-13 08:58 UTC, OskaMathis commented on flyway/sql/V1.0.0__init.sql
> +    COMMENT = 'ユーザトランザクション'
なるほど、事情は把握しました！
フォーマッタにかけた結果であれば仕方ないですね:sweat:

2022-04-13 09:47 UTC, OskaMathis commented on flyway/sql/V1.0.0__init.sql
> +    date    datetime DEFAULT CURRENT_TIMESTAMP COMMENT '投稿日付',
[nits]
超細かいですが、datetimeなので日付じゃなくて日時ですね

```suggestion
    date    datetime DEFAULT CURRENT_TIMESTAMP COMMENT '投稿日時',
```

2022-04-13 09:54 UTC, mizutoki79 commented
ちなみにユーザーや投稿の削除は無いですか？

2022-04-14 01:14 UTC, arima0714 commented
> ちなみにユーザーや投稿の削除は無いですか？

必須機能に入っていないので、今のところはないです。

2022-04-14 02:51 UTC, OskaMathis commented on flyway/sql/V1.0.0__init.sql
> +    date    datetime DEFAULT CURRENT_TIMESTAMP COMMENT '投稿日時',
すみません、1回で指摘できれば良かったんですが、再レビューして気づいた点書いておきます。

* `users.created_at` と命名を揃えておいた方が分かりやすいので、`posts.date`,`likes.date` は それぞれ `posted_at`, `liked_at` とかにしてみても良いかも
* そもそもdatetime型なのにカラム名がdateなのが違和感あります
  * 今後アプリケーション側の要件が変わって時刻も出したいとなったときに困るので、合わせるならカラム名の方をdatetimeにする方が良さそう

2022-04-14 02:54 UTC, OskaMathis commented
> 必須機能に入っていないので、今のところはないです。
開発スケジュールに余裕があれば追加を検討しても良さそうですね
CRUDを一通り実装するという意味で、ユーザ設定の更新とかもあって良さそう

2022-04-14 03:00 UTC, mizutoki79 commented on flyway/sql/V1.0.0__init.sql
> +    PRIMARY KEY (post_id, user_id)
参考までに
https://use-the-index-luke.com/ja/sql/where-clause/the-equals-operator/concatenated-keys
マルチカラムインデックス(プライマリーに限らず)はその順番も重要な意味を持ちます。
先頭のインデックスから順番に途中までのインデックスを使うことはできます(今回だとpost_idのみとしてもインデックスを使える)が、
途中を抜かして後ろのインデックスを使うことはできません(今回だとpost_idを使わずにuser_idだけをインデックスとして使うことはできない)
そのため、どういうクエリを投げるかと言うのを検討した上で順番を意識して定義してください。
たとえば、投稿に対してイイネしたユーザー一覧を出すならpost_idで検索するので、(post_id, user_id)の順
ユーザーからイイネした投稿一覧を出すならuser_idで検索するので、(user_id, post_id)の順が良いですね

2022-04-14 05:03 UTC, mizutoki79 commented on flyway/sql/V1.0.0__init.sql
> +    PRIMARY KEY (post_id, user_id)
[9dd06d9](https://github.com/arima0714/SaladBoard/pull/1/commits/9dd06d9721d66346a77f084fbcda10b66c45ca77)
これは参考情報であって、直してほしいという指摘では無かったのですが(user_id, post_id)の順番に変えた意図はありますか？

2022-04-14 05:39 UTC, arima0714 commented on flyway/sql/V1.0.0__init.sql
> +    PRIMARY KEY (post_id, user_id)
「投稿に対してイイネしたユーザー一覧を出す」の方がありえるかなと思ったので、採用しました。現在は @OskaMathis がクライアントなので今後変わる可能性があります。

2022-04-14 05:45 UTC, mizutoki79 commented on flyway/sql/V1.0.0__init.sql
> +    PRIMARY KEY (post_id, user_id)
回答ありがとうございます。
少なくとも今の画面設計で、https://cacoo.com/diagrams/MdP5Vhx8flBhVyWM/26018
イイネ数:likes.post_id が同じものの個数 というものが追加されていて、これはpost_idだけで検索することになると思います。
post_idだけ、user_idだけでそれぞれ検索することがある場合にはこの主キーだけでは実現できないので、主キーとは別に貼るのも手です。

2022-04-14 09:10 UTC, OskaMathis approved these changes

2022-04-14 09:10 UTC, mizutoki79 approved these changes

2022-04-14 09:12 UTC, nozawama approved these changes

2022-04-18 02:08 UTC, merged